[package]
name = "egui-winit"
version = "0.1.0"
authors = ["evopen <520dhh@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = "0.3.0"
winit = "0.23.0"
env_logger = "0.8.1"
log = "0.4.11"
